### ISSUE TITLE
CoE path 2 completion not detected

### ISSUE THREAD

**Issue by noodlewiz** [SamHurne/gw2pao#10]
I'm using PAO v3.1, and the dungeon tracker does not correctly detect completion of CoE path 2. Both path 1 and 3 are working as intended, with check marks after completion.

While running path 2, the dungeon tracker highlights CoE path 3. After the run is finished, path 2 does not get a check mark, neither does path 3.

The dungeon timer also does not start automatically for path 2, but does for path 1 and 3.

**Comment by noodlewiz** [comment]
Upon further testing, the dungeon timer does start and stop properly for path 2. However, unlike other paths, path 2 remains at 0:00:00.00 under Settings/Dungeons/Best Times.

I also did Arah story yesterday, but completion is also not detected (no check mark). Best Times also remains at zero.

**Comment by SamHurne** [comment]
Yes, there appears to be a few other dungeon paths with issues as well. I am working on implementing a new method of start/end detection which I expect will resolve the problems.

**Comment by SamHurne** [comment]
Closing as fixed in release v3.2. If additional path detection issues are discovered, we can open issues for those.
