### ISSUE TITLE
Gw2 PAO Crashing on zoning

### ISSUE THREAD

**Issue by quongping** [SamHurne/gw2pao#17]
Whenever I zone to a new map, PAO crashes or becomes unresponsive.

**Comment by SamHurne** [comment]
Any chance you can provide log files? Just using something like http://pastebin.com/ would work fine. If you provide those, I should be able to tell why it's crashing.

**Comment by quongping** [comment]
http://pastebin.com/AgFxWrWr

Think the log only shows me restarting the program. But from what I've noticed is that if I have the Zone Completion Assistant overlay open while changing zones, it causes it to become unresponsive. Last night I would close the Zone completion overlay before I zone and it didn't seem to cause any issues.

**Comment by Hoshiyuu** [comment]
I can second this issue. Every now and then the program would freeze completely on zone changes. I've tried all available installation version.

**Comment by SamHurne** [comment]
>I can second this issue. Every now and then the program would freeze completely on zone changes. I've tried all available installation version.

Do you also only see this when the Zone Completion Assistant window is open?

**Comment by Hoshiyuu** [comment]
Yes, but I am not 100% sure. I'll go warp around with the window off and report back.

**Comment by Hoshiyuu** [comment]
@SamHurne Yes, GW2PAO stopped freezing up completely once I closed Zone Completion Assistant, stable through constant warping between waypoints and maps.

I think due to the way I have to force end process every time GW2PAO freezes up, there is no helpful log for it. The log would be missing "program shutting down" entry and just have a new Application starting entry. Let me know if there is anything I can report to help.

**Comment by SamHurne** [comment]
>@SamHurne Yes, GW2PAO stopped freezing up completely once I closed Zone Completion Assistant, stable through constant warping between waypoints and maps.

Ok, thanks, that's helpful information. I'll definitely be looking into this more.

**Comment by ddreier** [comment]
FWIW, I'm able to get it to crash consistently by clearing out an entire zone in the Zone Completion Assistant and zoning out immediately or within a minute or two. Plus random crashes here and there.

**Comment by SamHurne** [comment]
Pretty sure I've found the issue. Thanks for the information all! A fix for this will be in version 3.2. Unfortunately, there's no work around that you guys can do until I release that, but 3.2 will be coming very soon.

**Comment by Hoshiyuu** [comment]
Thank you so much for your work! I only use PAO to free roam explore and
pickup nearby point of interests,I can't tell you how happy I am knowing I
won't have the freezing issue soon.

**Comment by SamHurne** [comment]
Closing as fixed in release 3.2. If this issue occurs again, we can re-open this, but I'm confident that this is fixed.
