### ISSUE TITLE
TS Overlay - Names stuck displaying

### ISSUE THREAD

**Issue by CJICantLie** [SamHurne/gw2pao#24]
Separate issue from the other one reported:

Every time I have the TS overlay open with version 3.4:

*There will be 2-3 random names stuck displaying as if they are speaking, when they are not.  

*It will display their names more than once when they do actually speak. 

I have attempted clearing it in multiple ways:

*By turning on interaction and closing the window, and reopening it.

*By toggling the window using the TS overlay hotkey.

*By closing the program and reopening it, and relaunching the TS overlay.

This issue did not exist in previous version, 3.3, nor does it exist when reverted back to 3.3.

**Comment by SamHurne** [comment]
Well shoot. I will look into getting this fixed ASAP.

**Comment by SamHurne** [comment]
Fixed (quick fix) in e3b2cbaae72c2df825da31b6c3d287f953f5e8ad

Release build in progress...
