### ISSUE TITLE
Salvage Helper Position Save

### ISSUE THREAD

**Issue by CJICantLie** [SamHurne/gw2pao#28]
The Ectoplasm Salvage Helper's position isn't saving correctly between close/open of the application.  All other windows seem to be fine.  After a bit of testing different saved positions, it seems it saves the X axis correctly, not the Y axis.

**Comment by SamHurne** [comment]
Fixed with commit 8b0ddc853162952d97a1610a6209480041bbaf14

**Comment by SamHurne** [comment]
Release posted!
