### ISSUE TITLE
NullReferenceException in CommerceController

### ISSUE THREAD

**Issue by Exolius** [SamHurne/gw2pao#35]
Loading GW2 PAO crashes when guild wars 2 is open, I have attached the log file for me and also a friend who is having the same problem.

http://pastebin.com/a7PdsD6d

http://pastebin.com/eBaGsq6m

**Comment by seiyria** [comment]
Bad Gateway suggests that there was an internet problem at the time. I'm not having any crashes with PAO and HoT currently.

**Comment by Keridos** [comment]
Crashes very often for me as well.

**Comment by SamHurne** [comment]
Looks like the bad gateway issues led to a `NullReferenceException` in the `CommerceController`. The whole application could use a good review to check for these possible situations, but I've found this particular null reference location, so a fix for this one will be in the next release.

**Comment by SamHurne** [comment]
This should now be fixed with commit 7f2470f295605baee4d07a2b4663ea27c377a06a.

**Comment by SamHurne** [comment]
Release posted!
