### ISSUE TITLE
hope can work with obs

### ISSUE THREAD

**Issue by bluelovers** [SamHurne/gw2pao#36]
hope can work with obs

and can i move overlay icon ?
cos it block my game menu lol

**Comment by SamHurne** [comment]
What is "obs"?

And yes, [you can move the overlay icon](https://github.com/SamHurne/gw2pao/wiki/Startup-and-General-Usage#overlay-menu-icon).

**Comment by bluelovers** [comment]
1. Open Broadcaster Software
2. i can't move "main icon" (the top right one)

**Comment by SamHurne** [comment]
Closing this for now... If there is a problem with the PAO and it's use with OBS, feel free to make a new issue for that.
