### ISSUE TITLE
Automatically hide button when GW2 isn't focused doesn't work with the 64bit client

### ISSUE THREAD

**Issue by Unspec7** [SamHurne/gw2pao#37]
Since the release of the 64bit client, the option to automatically hide the button when GW2 isn't focused or running no longer works. It stays hidden, even if GW2 is the current focus.

**Comment by SamHurne** [comment]
Pretty sure this is due to the 64-bit client process having a name of "Gw2-64.exe" instead of just "Gw2.exe". I'll just need to update the code to try both names.

**Comment by Unspec7** [comment]
Pretty much what I figured, just thought I'd bring it to your attention

**Comment by StevenLiekens** [comment]
Sounds like you can work around this by renaming the executable to "Gw2.exe".

**Comment by Tyrrrz** [comment]
Proposed fix: https://github.com/Tyrrrz/gw2pao/commit/05f2eb2706893e40ed7899451a8283bc7c8fb383

**Comment by R3xz** [comment]
Has anyone tried the proposed fix that Tyrrrz posted?

**Comment by SamHurne** [comment]
Fixed with commit a4092b1637d3e9a2f548f9e517056241f58520b3

**Comment by SamHurne** [comment]
Release Posted!
