### ISSUE TITLE
WvW borderland map info not correct

### ISSUE THREAD

**Issue by MrsKryten** [SamHurne/gw2pao#45]
Alpine maps were reintroduced in Tuesday's patch and I think that has affected the WvW tracker. The info for Eternal Battlegrounds seems accurate so it's just alpine borderland maps that have wrong objective names, RI and owners.

**Comment by SamHurne** [comment]
I'm actually surprised that the existing IDs and everything are still accurate for the Alpine maps. But yes, this is one of many things that needs some updates.

**Comment by SamHurne** [comment]
Looks like objectives across the different borderlands maps now have the same IDs. For example, the northern camp on each map used to have a unique ID, but the north camp has the exact same ID across all 3 maps. So, I'll just need to make an update to handle that change.

**Comment by SamHurne** [comment]
This should now be fixed with commit de22403a78a96010b2ca0a1bfc44d34524e20cc3. Still doing a bit of testing to confirm I got all of the IDs correct, but this will be in the upcoming maintenance release.

**Comment by SamHurne** [comment]
Release posted!

**Comment by MrsKryten** [comment]
Thank you so much for the fix!!!
