### ISSUE TITLE
How to move overlay icon?

### ISSUE THREAD

**Issue by bluelovers** [SamHurne/gw2pao#49]
![20161109-042045-2](https://cloud.githubusercontent.com/assets/167966/20115772/87ac6314-a634-11e6-8d0d-f151062cde0e.png)

overlay icon almost block F11 icon

---

does ts chat can have option for keep text msg without auto clear

**Comment by joaroyen** [comment]
Here is a workaround for moving the overlay icon (tested on Windows 10):
- Click on the icon to open the gw2pao menu
- Press ALT + Spacebar to open the Windows System Menu
- Select Move
- Click on one of the arrow keys to start moving the icon
Then you should be able to move the overlay icon using the mouse, or continue to use the arrow keys.

**Comment by SamHurne** [comment]
You should also be able to re-position the overlay icon by holding Ctrl and click-dragging the icon. Does that not work?

**Comment by bluelovers** [comment]
thx, it work
