### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by ecspresso** [SamHurne/gw2pao#58]
I am unable to build, I think I need some guidance. Do I need to set anything before I build?

"error CS0006: Metadata file '\gw2pao-develop\GW2PAO\bin\Debug\GW2PAO.exe'"

**Comment by SamHurne** [comment]
Have you taken a look at the [How-to-Build Guide](https://github.com/SamHurne/gw2pao/wiki/How-to-Build) in the Wiki yet?

What version of Visual Studio are you using? Have you restored all of the nuget packages?

**Comment by ecspresso** [comment]
I was using the latest version (2017). I downloaded and installed VS Community 2015 instead, right clicked the solution and chose "Restore NuGet Packages" and built the solution after that. This time it worked. Thanks for taking the time to respond!
