### ISSUE TITLE
Taidha Covington wrong waypoint code.

### ISSUE THREAD

**Issue by Andrius2012** [SamHurne/gw2pao#8]
Hi guys, when you click on "copy waypoint code" on Taidha event at the event tracker, it gives to you the waypoint code [&BNQCAAA=] but I think it should give you this one [&BKgBAAA=]

**Comment by SamHurne** [comment]
Yup. Good catch. I'll have a fix in for the next release.

In the mean time, you're welcome to fix this for yourself as well by editing the `AdjustedEventTimeTable.xml` or `StandardEventTimeTable.xml` files (depending on which you use, standard vs adjusted). The waypoint codes used by the program for the world events are stored in these files in the `<Waypoint></Waypoint>` tags.

**Comment by SamHurne** [comment]
Fixed with commit 9174995176bd451480726fdf0b50759d19d98898

**Comment by Andrius2012** [comment]
thanks dude, gj!!
