### ISSUE TITLE
icon is gone

### ISSUE THREAD

**Issue by saelfaer** [SamHurne/gw2pao#9]
So,

your flyout menu has an option to 'hide' or 'show' the overlay icon.
but what is it good for? and after hiding it, how do you get back in the overlay. ...
searched around on the site or code but couldn't really find any shortcut or anything...

**Comment by SamHurne** [comment]
If you hide the Overlay Icon, you can turn it back on by using the icon in the system tray. The System Try icon is always available if the program is running.

**Comment by saelfaer** [comment]
damn, systray ofcourse... spent too much time on linux as of late.
was already going through register to find where you save the state of that showIcon flag :)
systray is easier thanks!
